#
# BudgetTracker Dockerfile for UI
#
FROM nginx:stable


# Copy a configuration file from the current directory
ADD nginx.conf /etc/nginx/

#RUN rm /var/www/html/index.html
 VOLUME [ "/usr/share/nginx/html/" ]
